name: recaptcha_verifier
version: 0.0.1
description: Google ReCaptcha server-side verifier
author: Aleksey Danilevskiy<alexey.danilevsky@gmail.com>
homepage:
documentation:

dependencies:
  http: ^0.11.3+16

dev_dependencies:
  test: ^0.12.26

